services:
  nest-base:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'docker_nest_base'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
